### ISSUE TITLE
Dropbox not giving "No Expiration Token"

### ISSUE THREAD

**Issue by anoxdleo** [ArnabXD/Dropbox-Index#74]
Dropbox is not giving Long Lived Token to use, any solution for this ? @ArnabXD

**Comment by ArnabXD** [comment]
I think the tokens don't have an expiration time now. I haven't generated one for long and I can't remember how it used to be. But when I tried generating a new token, I didn't notice anything claiming the expiration of the token, so I believe the test token is always live.

**Comment by newd2459** [comment]
hi , pls try again i talked to dropbox support today and they just replied that long -lived tokens are not available anymore, from sept 2021 they have started the update and only short lived tokens will be given , to automate the process of obtaining new token we can get a refresh token and using api we can get new short lived token. These are the links they provided -
https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens#updating-access-token-type
https://www.dropbox.com/developers/documentation/http/documentation#authorization
https://developers.dropbox.com/oauth-guide

**Comment by newd2459** [comment]
@ArnabXD these are the exact words of support
Dropbox is in the process of switching to only issuing short-lived access tokens (and optional refresh tokens) instead of long-lived access tokens. You can find [more information on this migration here](https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens#updating-access-token-type).

Apps can still get long-term access by requesting "offline" access though, in which case the app receives a "refresh token" that can be used to retrieve new short-lived access tokens as needed, without further manual user intervention. You can find more information in the [OAuth Guide](https://developers.dropbox.com/oauth-guide) and [authorization documentation](https://www.dropbox.com/developers/documentation/http/documentation#authorization).

For reference, while the creation of new long-lived access tokens is now deprecated, we don't currently have a plan to disable existing long-lived access tokens. (If that changes, we will of course announce that ahead of time.) That being the case, you can continue using existing long-lived access token(s) without interruption, if you have any. Also, note though that after the change you won't be able to create new long-lived access tokens.

While the change began on September 30th 2021, we're releasing it gradually, so you may not have seen your app(s) affected until now. Once it applies to your app, it would apply regardless of the "Access token expiration" setting for your app, and that setting may no longer be available for your app.

Note that this is something that would need to be implemented by the programmer of the app though, so if you are not the programmer responsible for this integration, you may need to get an update from them to support this.
